version: "3.9" 
services:
  organogramapi:
    image: organogramapi
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MY_SQL_ROOT_HOST=mysql
      - MYSQL_USER=organogramapi
      - MYSQL_DATABASE=organogram
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:



